"""Category: Ethernet — wired adapter driver-level optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Ethernet", win_default="7,8,10,11")
CATEGORY = "Ethernet"

PS = "powershell -NoProfile -ExecutionPolicy Bypass -Command"

TWEAKS = validate_module("ethernet", [
    T("eth-001", "Disable Adapter Power Management",
      "Turns off all power-saving on the wired adapter.",
      actions=[("cmd", f'{PS} "Disable-NetAdapterPowerManagement -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Enable-NetAdapterPowerManagement -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      why="Power management can put the adapter into low-power modes that add latency spikes.",
      changes="Disables adapter power management.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["power", "adapter", "ethernet"]),

    T("eth-004", "Disable Large Send Offload IPv4",
      "Turns off LSOv4 segmentation offload.",
      actions=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Ethernet*\' -IPv4Enabled $false -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterLso -Name \'Ethernet*\' -IPv4Enabled $true -ErrorAction SilentlyContinue"')],
      why="Offloading segmentation to the NIC can add micro-burst latency on some hardware.",
      changes="Disables LSO IPv4.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["lso", "offload", "tcp"]),
    T("eth-005", "Enable RSS on Adapter",
      "Enables receive-side scaling on the wired adapter.",
      actions=[("cmd", f'{PS} "Set-NetAdapterRss -Name \'Ethernet*\' -Enabled $true -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterRss -Name \'Ethernet*\' -Enabled $false -ErrorAction SilentlyContinue"')],
      why="Spreads receive processing across CPU cores to avoid single-core saturation.",
      changes="Enables adapter RSS.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["rss", "cpu", "receive"]),
    T("eth-006", "Disable Flow Control",
      "Turns off Ethernet flow control.",
      actions=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Flow Control\' -DisplayValue \'Disabled\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Flow Control\' -DisplayValue \'Enabled\' -ErrorAction SilentlyContinue"')],
      why="Pause frames can stall the adapter at the worst moments; disabled flow control is typical for gaming.",
      changes="Disables flow control.",
      risk="low", impact="low", recommended="optional", admin=True,
      tags=["flowcontrol", "pause", "ethernet"]),

    T("eth-008", "Disable Energy Efficient Ethernet",
      "Turns off EEE/Green Ethernet power saving.",
      actions=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Energy Efficient Ethernet\' -DisplayValue \'Disabled\' -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterAdvancedProperty -Name \'Ethernet*\' -DisplayName \'Energy Efficient Ethernet\' -DisplayValue \'Enabled\' -ErrorAction SilentlyContinue"')],
      why="EEE drops the link into low-power idle that re-negotiates with latency when traffic resumes.",
      changes="Disables Energy Efficient Ethernet.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["eee", "green", "power"]),
    T("eth-009", "Disable Wake on Magic Packet",
      "Turns off Wake-on-LAN wake on magic packet.",
      actions=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Ethernet*\' -WakeOnMagicPacket Disabled -ErrorAction SilentlyContinue"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterPowerManagement -Name \'Ethernet*\' -WakeOnMagicPacket Enabled -ErrorAction SilentlyContinue"')],
      why="Removes the always-listening wake path that keeps the adapter powered in sleep.",
      changes="Disables Wake-on-Magic-Packet.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["wol", "magic", "wake"]),
    T("eth-010", "Raise Receive Buffers",
      "Increases the adapter receive ring buffer size.",
      actions=[("cmd", f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'ReceiveBuffers\' -ErrorAction Stop | Set-NetAdapterAdvancedProperty -RegistryKeyword \'ReceiveBuffers\' -RegistryValue 2048"')],
      revert=[("cmd", f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'ReceiveBuffers\' -ErrorAction Stop | Set-NetAdapterAdvancedProperty -RegistryKeyword \'ReceiveBuffers\' -RegistryValue 512"')],
      why="Larger receive buffers reduce dropped packets during traffic bursts.",
      changes="Sets ReceiveBuffers to 2048.",
      risk="low", impact="low", recommended="recommended", admin=True,
      support=[{"cmd": f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'ReceiveBuffers\' -ErrorAction Stop | Select-Object -ExpandProperty RegistryValue"',
                "label": "Adapter does not expose a ReceiveBuffers advanced property"}],
      updated="2026-09-27",
      tags=["buffers", "receive", "drop"]),
    T("eth-011", "Raise Transmit Buffers",
      "Increases the adapter transmit ring buffer size.",
      actions=[("cmd", f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'TransmitBuffers\' -ErrorAction Stop | Set-NetAdapterAdvancedProperty -RegistryKeyword \'TransmitBuffers\' -RegistryValue 2048"')],
      revert=[("cmd", f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'TransmitBuffers\' -ErrorAction Stop | Set-NetAdapterAdvancedProperty -RegistryKeyword \'TransmitBuffers\' -RegistryValue 512"')],
      why="Larger transmit buffers smooth out bursty game traffic.",
      changes="Sets TransmitBuffers to 2048.",
      risk="low", impact="low", recommended="recommended", admin=True,
      support=[{"cmd": f'{PS} "Get-NetAdapterAdvancedProperty -Name (Get-NetAdapter -Physical).Name -RegistryKeyword \'TransmitBuffers\' -ErrorAction Stop | Select-Object -ExpandProperty RegistryValue"',
                "label": "Adapter does not expose a TransmitBuffers advanced property"}],
      updated="2026-09-27",
      tags=["buffers", "transmit", "burst"]),
    T("eth-012", "Reset Ethernet Adapter",
      "Restarts the wired network adapter.",
      actions=[("cmd", f'{PS} "Restart-NetAdapter -Name \'Ethernet*\' -ErrorAction SilentlyContinue"')],
      revert=[("guidance", "Adapter restart is non-destructive.")],
      why="Clears stuck driver state and re-negotiates the link.",
      changes="Restarts the Ethernet adapter.",
      risk="safe", impact="moderate", recommended="optional", admin=True, confirm=True,
      tags=["reset", "adapter", "restart"]),
    T("eth-013", "Full-Duplex Link Check",
      "Reports the negotiated link speed and duplex mode.",
      actions=[("cmd", f'{PS} "Get-NetAdapter -Name \'Ethernet*\' | Format-Table Name,LinkSpeed,FullDuplex -AutoSize"')],
      revert=[("guidance", "Read-only report.")],
      why="A 100 Mbps or half-duplex link is often a faulty cable or port, not a Windows problem.",
      changes="Shows the adapter link report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["duplex", "speed", "link"]),
    T("eth-014", "Disable IPv6 Large Send Offload",
      "Turns off IPv6 LSO independently of IPv4.",
      actions=[("cmd", f'{PS} "Set-NetAdapterLso -Name (Get-NetAdapter -Physical).Name -IPv6Enabled $false"')],
      revert=[("cmd", f'{PS} "Set-NetAdapterLso -Name (Get-NetAdapter -Physical).Name -IPv6Enabled $true"')],
      why="IPv6 LSO offload should be disabled independently from IPv4 when the NIC's IPv6 offload is the problem.",
      changes="Disables IPv6 LSO on the active adapter.",
      risk="low", impact="low", recommended="optional", admin=True,
      support=[{"cmd": f'{PS} "Get-NetAdapterLso -Name (Get-NetAdapter -Physical).Name | Where-Object {{ $_.IPv6Enabled -ne $null }}"',
                "label": "Adapter does not expose an IPv6 LSO property"}],
      updated="2026-09-27",
      tags=["lso", "ipv6", "offload"]),
    T("eth-015", "Disable Adapter Power-Off (Allow Computer to Turn Off)",
      "Disables 'Allow the computer to turn off this device' on the wired adapter.",
      actions=[("cmd", f'{PS} "Disable-NetAdapterPowerManagement -Name (Get-NetAdapter -Physical).Name -AllowComputerToTurnOffDevice"')],
      revert=[("cmd", f'{PS} "Enable-NetAdapterPowerManagement -Name (Get-NetAdapter -Physical).Name -AllowComputerToTurnOffDevice"')],
      why="The adapter's own 'turn off to save power' switch can drop the link during short idle gaps.",
      changes="Disables the adapter's allow-power-off switch (power wake support kept).",
      risk="safe", impact="low", recommended="recommended", admin=True,
      support=[{"cmd": f'{PS} "Get-NetAdapterPowerManagement -Name (Get-NetAdapter -Physical).Name -ErrorAction Stop | Select-Object -ExpandProperty AllowComputerToTurnOffDevice"',
                "label": "Adapter does not expose AllowComputerToTurnOffDevice"}],
      updated="2026-09-27",
      tags=["power", "adapter", "ethernet"]),

])
