"""Category: NVIDIA — GeForce driver and NVIDIA Control Panel guidance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("NVIDIA", win_default="7,8,10,11")
CATEGORY = "NVIDIA"

TWEAKS = validate_module("nvidia", [
    T("nv-001", "Enable Persistence Mode",
      "Keeps the NVIDIA driver resident to lower launch stalls.",
      actions=[("cmd", "nvidia-smi -pm 1")],
      revert=[("cmd", "nvidia-smi -pm 0")],
      why="Persistence mode avoids reloading driver state between applications.",
      changes="Sets GPU persistence mode on.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["persistence", "driver", "nvidia"]),
    T("nv-002", "Reset Auto Boost Defaults",
      "Returns GPU boost clocks to driver defaults.",
      actions=[("cmd", "nvidia-smi --auto-boost-default=0")],
      revert=[("cmd", "nvidia-smi --auto-boost-default=1")],
      why="Clears custom boost state so the GPU boost algorithm runs normally.",
      changes="Resets auto-boost settings.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["boost", "clock", "nvidia"]),
    T("nv-003", "Enable PowerMizer",
      "Allows the driver to manage GPU power states.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PowerMizerEnable", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000", "PowerMizerEnable")],
      why="PowerMizer handles GPU clock transitions on GeForce cards.",
      changes="Enables PowerMizer control.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["powermizer", "power", "clock"]),

    T("nv-005", "Disable NVIDIA Telemetry Service",
      "Stops the NVIDIA telemetry background service.",
      actions=[("sc", "disable", "NvTelemetryContainer")],
      revert=[("sc", "enable", "NvTelemetryContainer")],
      why="Telemetry services poll in the background and add wake-ups.",
      changes="Disables NvTelemetryContainer.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["telemetry", "service", "nvidia"]),
    T("nv-007", "Low Latency Mode Ultra",
      "Sets NVIDIA Low Latency Mode to Ultra in the driver profile.",
      actions=[("guidance", "NVIDIA driver profile setting: set 'Low Latency Mode' to 'Ultra' (spec: LowLatencyMode=Ultra). The driver submits frames just-in-time to the GPU for the lowest input delay. Applies in NVIDIA Control Panel > Manage 3D Settings, or per-game profile.")],
      revert=[("guidance", "Set 'Low Latency Mode' back to 'Off'.")],
      why="Low Latency Mode trims queued frames before they reach the GPU.",
      changes="Shows Low Latency Mode Ultra guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["latency", "reflex", "nvidia", "drvprofile"]),

    T("nv-009", "G-SYNC Compatibility Check",
      "Guidance to verify G-SYNC on a monitor.",
      actions=[("guidance", "In NVIDIA Control Panel > Set up G-SYNC, enable G-SYNC for your monitor. Use the G-SYNC pendulum demo or 'G-SYNC indicator' overlay to confirm it is active in-game.")],
      revert=[("guidance", "Disable G-SYNC.")],
      why="A G-SYNC monitor not detected is a missed smoothness upgrade.",
      changes="Shows G-SYNC guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["gsync", "sync", "monitor"]),
    T("nv-010", "Disable DSR",
      "Disables NVIDIA DSR via registry.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "DsrFlags", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "DsrFlags")],
      why="DSR multiplies render cost and reduces effective refresh headroom.",
      changes="Sets DsrFlags to 0 (DSR disabled).",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["dsr", "resolution", "supersample"]),
    T("nv-011", "Threaded Optimization Auto",
      "Sets NVIDIA threaded optimization to Auto in the driver profile.",
      actions=[("guidance", "NVIDIA driver profile setting: set 'Threaded Optimization' to 'Auto' (spec: ThreadedOptimization=Auto). Driver heuristics pick the right CPU threading mode per title. Applies in NVIDIA Control Panel > Manage 3D Settings.")],
      revert=[("guidance", "Set 'Threaded Optimization' to 'Off'.")],
      why="Driver heuristics usually pick the right threading mode.",
      changes="Shows Threaded Optimization Auto guidance.",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["threads", "cpu", "optimization", "drvprofile"]),
    T("nv-012", "Max Pre-Rendered Frames 1",
      "Sets maximum pre-rendered frames to 1 via registry.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "MaxPreRenderedFrames", 1, "DWORD")],
      revert=[("regdel", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\*\Curver", "MaxPreRenderedFrames")],
      why="Fewer queued frames = less latency but can raise CPU cost.",
      changes="Sets MaxPreRenderedFrames to 1.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["frames", "queue", "latency"]),
    T("nv-013", "Driver Update Guidance",
      "Guidance for stable driver updates.",
      actions=[("guidance", "Use the latest Game Ready driver or a verified Studio driver. Avoid beta drivers for ranked play; install via 'Clean install' to reset stale settings.")],
      revert=[("guidance", "Roll back the driver.")],
      why="New game releases rely on updated drivers, but betas can regress.",
      changes="Shows driver guidance.",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["driver", "update", "game ready"]),
    T("nv-014", "Disable Ansel",
      "Guidance to disable the Ansel screenshot tool.",
      actions=[("guidance", "If you do not use NVIDIA Ansel (free camera screenshots), avoid launching it — it can pause the render loop. There is no registry toggle; just do not invoke Alt+F2.")],
      revert=[("guidance", "No change to revert.")],
      why="Ansel pauses game rendering while active.",
      changes="Shows Ansel guidance.",
      risk="safe", impact="very low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["ansel", "screenshot", "overlay"]),
    T("nv-015", "Reflex Low Latency Guidance",
      "Guidance for NVIDIA Reflex in supported games.",
      actions=[("guidance", "Enable NVIDIA Reflex 'On + Boost' in supported games. Reflex aligns CPU and GPU work and trims render queue latency — the biggest measurable input-lag reduction available.")],
      revert=[("guidance", "Turn Reflex off in the game.")],
      why="Reflex reduces system latency by coordinating the CPU and GPU.",
      changes="Shows Reflex guidance.",
      risk="safe", impact="high", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["reflex", "latency", "esports"]),

    T("nv-018", "Disable NVIDIA Logging Services",
      "Stops and disables the NVIDIA logging and monitoring services.",
      actions=[("svc", "NvTmMon", "disabled"), ("svc", "NvTmRep", "disabled"), ("svc", "NvVapI", "disabled"), ("svc", "NVDisplay.Container", "disabled")],
      revert=[("svc", "NvTmMon", "manual"), ("svc", "NvTmRep", "manual"), ("svc", "NvVapI", "manual"), ("svc", "NVDisplay.Container", "manual")],
      why="NVIDIA background services poll GPU state and write logs; disabling them removes periodic wake-ups and disk writes.",
      changes="Disables NVIDIA logging and display container services.",
      risk="safe", impact="low", recommended="optional", admin=True,
      when={"gpu": ["nvidia"]},
      tags=["services", "logging", "background"]),

    T("nv-019", "Power Management Mode - Prefer Maximum Performance",
      "Sets NVIDIA power management mode to prefer maximum performance.",
      actions=[("guidance", "NVIDIA driver profile setting: set 'Power Management Mode' to 'Prefer maximum performance' (spec: PowerManagementMode=PreferMaximumPerformance). The GPU stays at full clocks instead of dropping to power-saving states. Applies in NVIDIA Control Panel > Manage 3D Settings, or per-game profile.")],
      revert=[("guidance", "Set 'Power Management Mode' to 'Optimal power' or 'Adaptive'.")],
      why="Throttled GPU power states cause frame-time spikes.",
      changes="Shows PPM guidance (Prefer maximum performance).",
      risk="safe", impact="moderate", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["power", "clocks", "nvidia", "drvprofile"]),
    T("nv-020", "Shader Cache Size - Driver Default",
      "Keeps NVIDIA shader cache size at the driver default.",
      actions=[("guidance", "NVIDIA driver profile setting: set 'Shader Cache Size' to 'Driver Default' (spec: ShaderCacheSize=DriverDefault). The driver manages the on-disk shader cache automatically, avoiding DX12 recompilation stutter without wasting disk space. Applies in NVIDIA Control Panel > Manage 3D Settings.")],
      revert=[("guidance", "Change the shader cache size to a manual value.")],
      why="A mismanaged shader cache forces recompiles mid-game.",
      changes="Shows shader cache guidance (Driver Default).",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["shaders", "cache", "stutter", "drvprofile"]),
    T("nv-021", "Texture Filtering Quality - High Performance",
      "Sets NVIDIA texture filtering quality to high performance.",
      actions=[("guidance", "NVIDIA driver profile setting: set 'Texture Filtering - Quality' to 'High Performance' (spec: TextureFilteringQuality=HighPerformance). Trades a tiny amount of texture sharpness for noticeably higher FPS. Applies in NVIDIA Control Panel > Manage 3D Settings, or per-game profile.")],
      revert=[("guidance", "Set 'Texture Filtering - Quality' back to 'Quality'.")],
      why="Quality filtering costs fill rate for a subtle visual gain.",
      changes="Shows texture filtering guidance (High Performance).",
      risk="safe", impact="low", recommended="recommended",
      when={"gpu": ["nvidia"]},
      tags=["textures", "filtering", "fps", "drvprofile"]),

])
