"""Category: Security & Performance — security settings that affect performance."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("Security & Performance", win_default="10,11")
CATEGORY = "Security & Performance"

TWEAKS = validate_module("security_perf", [
    T("sec-001", "Add Game Folder to Defender Exclusions",
      "Excludes game folders from real-time scanning.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", r"C:\Games", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths", r"C:\Games")],
      why="Real-time scanning of huge game folders steals disk and CPU time.",
      changes="Adds C:\\Games to Defender exclusions.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["defender", "exclusion", "antivirus"]),
    T("sec-002", "Exclude Game Processes",
      "Excludes game executables from scanning.",
      actions=[("reg", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Processes", "game.exe", 0, "DWORD")],
      revert=[("regdel", "HKLM", r"SOFTWARE\Microsoft\Windows Defender\Exclusions\Processes", "game.exe")],
      why="Process exclusions skip per-access scanning of the game's hot files.",
      changes="Adds game.exe to Defender process exclusions.",
      risk="safe", impact="low", recommended="optional", admin=True,
      tags=["defender", "process", "scan"]),
    T("sec-008", "Disable Remote Desktop",
      "Disables RDP if unused.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", 1, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Control\Terminal Server", "fDenyTSConnections", 0, "DWORD")],
      why="RDP listens on a network port and adds a small service cost.",
      changes="Disables Remote Desktop.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["rdp", "remote", "network"]),
    T("sec-009", "Disable SMB1 Protocol",
      "Disables the legacy SMB1 feature.",
      actions=[("cmd", "dism /online /disable-feature /featurename:SMB1Protocol /norestart")],
      revert=[("cmd", "dism /online /enable-feature /featurename:SMB1Protocol /all /norestart")],
      why="Removes a legacy network stack and its audit overhead.",
      changes="Disables SMB1.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["smb", "network", "legacy"]),
    T("sec-010", "Disable PowerShell Script Logging",
      "Disables PowerShell ScriptBlock Logging via Group Policy.",
      actions=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging", "EnableScriptBlockLogging", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging", "EnableScriptBlockLogging", 1, "DWORD")],
      why="Script logging adds per-command overhead in admin tooling.",
      changes="Disables PowerShell ScriptBlock Logging.",
      risk="safe", impact="very low", recommended="recommended", admin=True,
      tags=["powershell", "logging", "audit"]),
    T("sec-011", "Disable Network Discovery",
      "Disables network discovery.",
      actions=[("cmd", "powershell -NoProfile -Command Set-NetFirewallRule -DisplayGroup 'Network Discovery' -Enabled False")],
      revert=[("cmd", "powershell -NoProfile -Command Set-NetFirewallRule -DisplayGroup 'Network Discovery' -Enabled True")],
      why="Network discovery broadcasts and answers mDNS constantly.",
      changes="Disables Network Discovery firewall rules.",
      risk="safe", impact="very low", recommended="optional", admin=True,
      tags=["network", "discovery", "broadcast"]),
])
