"""Category: USB — controller, suspend and device optimizations."""
from __future__ import annotations

from ._base import make_T, validate_module

T = make_T("USB", win_default="7,8,10,11")
CATEGORY = "USB"

TWEAKS = validate_module("usb", [
    T("usb-001", "Disable USB Selective Suspend",
      "Turns off USB selective suspend in the active power scheme.",
      actions=[("power", "usb_selective", 0)],
      revert=[("power", "usb_selective", 1)],
      why="Selective suspend drops hubs to low-power mode, adding wake latency to mice and keyboards.",
      changes="Disables USB selective suspend on AC.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      tags=["usb", "suspend", "power"]),

    T("usb-003", "USB Device Report",
      "Lists USB controllers and devices with their status.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq 'USB' -or $_.Class -eq 'HIDClass' } | Format-Table FriendlyName,Status,Problem -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Surfaces USB devices in error state that cause intermittent input drops.",
      changes="Shows the USB device report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["usb", "report", "devices"]),
    T("usb-004", "USB Controller Report",
      "Lists the USB host controllers and their driver dates.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-CimInstance Win32_USBController | Format-Table Name,Manufacturer,Status -AutoSize\"")],
      revert=[("guidance", "Read-only report.")],
      why="Confirms the correct xHCI controller is active and in a healthy state.",
      changes="Shows the USB controller report.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["controller", "xhci", "usb"]),
    T("usb-006", "Disable USB Host Controller Power Management",
      "Disables power management on all USB host controllers to prevent input device sleep.",
      actions=[("regall", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}", "PnPCapabilities", 256, "DWORD")],
      revert=[("regdelall", "HKLM", r"SYSTEM\CurrentControlSet\Control\Class\{36fc9e60-c465-11cf-8056-444553540000}", "PnPCapabilities")],
      why="USB power management can drop an input device to sleep mid-session.",
      changes="Disables 'Allow the computer to turn off this device' on USB host controllers.",
      risk="safe", impact="moderate", recommended="recommended", admin=True,
      updated="2026-09-27",
      tags=["usb", "power", "input"]),


    T("usb-012", "Verify XHCI Controller",
      "Checks that the XHCI (USB 3) controller is the active host.",
      actions=[("cmd", "powershell -NoProfile -Command \"Get-PnpDevice -PresentOnly -Class USB | Where-Object { $_.FriendlyName -match 'Host Controller' } | Format-Table FriendlyName,Status -AutoSize\"")],
      revert=[("guidance", "Read-only check.")],
      why="Ensures Windows is using the modern xHCI stack rather than a legacy EHCI fallback.",
      changes="Shows the active host controller.",
      risk="safe", impact="very low", recommended="recommended",
      tags=["xhci", "host", "controller"]),

    T("usb-014", "Set USB Data Queue Size",
      "Sets the minimum USB transfer bytes to zero for lower latency.",
      actions=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\usb", "MinimumTransferBytes", 0, "DWORD")],
      revert=[("reg", "HKLM", r"SYSTEM\CurrentControlSet\Services\usb", "MinimumTransferBytes", 64, "DWORD")],
      why="Reducing the minimum transfer size removes unnecessary buffering that adds USB round-trip latency.",
      changes="Sets MinimumTransferBytes to 0.",
      risk="safe", impact="low", recommended="optional", admin=True,
      updated="2026-09-27",
      tags=["usb", "transfer", "latency"]),
    T("usb-015", "Disable USB Hub Power Management",
      "Disables 'Allow the computer to turn off this device' on selected USB hubs.",
      actions=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly -Class USB | Where-Object { $_.FriendlyName -match \'Hub\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; New-Item -Path $k -Force -ErrorAction SilentlyContinue | Out-Null; Set-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -Value 0 -Type DWord -ErrorAction SilentlyContinue }"')],
      revert=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly -Class USB | Where-Object { $_.FriendlyName -match \'Hub\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; Remove-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -ErrorAction SilentlyContinue }"')],
      why="A hub that powers down mid-session drops every attached device's inputs at once.",
      changes="Disables hub power-off on detected USB hubs.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      support=[{"cmd": 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly -Class USB | Where-Object { $_.FriendlyName -match \'Hub\' } | Select-Object -ExpandProperty InstanceId"',
                "label": "No present USB hub detected"}],
      updated="2026-09-27",
      tags=["hub", "power", "usb"]),
    T("usb-016", "Disable HID Keyboard/Mouse Power Management",
      "Disables 'Allow the computer to turn off this device' for detected HID keyboard and mouse instances.",
      actions=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'HIDClass\' -and $_.FriendlyName -match \'Keyboard|Mouse\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; New-Item -Path $k -Force -ErrorAction SilentlyContinue | Out-Null; Set-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -Value 0 -Type DWord -ErrorAction SilentlyContinue }"')],
      revert=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'HIDClass\' -and $_.FriendlyName -match \'Keyboard|Mouse\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; Remove-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -ErrorAction SilentlyContinue }"')],
      why="Input devices that sleep cause the first-move/last-keystroke hitch when the game needs them.",
      changes="Disables power-off on detected HID keyboard/mouse instances.",
      risk="safe", impact="low", recommended="recommended", admin=True,
      support=[{"cmd": 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'HIDClass\' -and $_.FriendlyName -match \'Keyboard|Mouse\' } | Select-Object -ExpandProperty InstanceId"',
                "label": "No present HID keyboard/mouse instance detected"}],
      updated="2026-09-27",
      tags=["hid", "keyboard", "mouse", "power"]),
    T("usb-017", "Disable Bluetooth HID Power Saving",
      "Disables power-saving on the Bluetooth HID adapter that serves BT keyboards and mice.",
      actions=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'Bluetooth\' -and $_.FriendlyName -match \'HID|Keyboards\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; New-Item -Path $k -Force -ErrorAction SilentlyContinue | Out-Null; Set-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -Value 0 -Type DWord -ErrorAction SilentlyContinue }"')],
      revert=[("cmd", 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'Bluetooth\' -and $_.FriendlyName -match \'HID|Keyboards\' } | ForEach-Object { $k = \'HKLM:\\SYSTEM\\CurrentControlSet\\Enum\\\' + $_.InstanceId + \'\\Device Parameters\'; Remove-ItemProperty -Path $k -Name \'EnhancedPowerManagementEnabled\' -ErrorAction SilentlyContinue }"')],
      why="Bluetooth HID adapters dropping to low power add lag bursts to wireless input.",
      changes="Disables power-off on detected Bluetooth HID adapters.",
      risk="safe", impact="low", recommended="optional", admin=True,
      support=[{"cmd": 'powershell -NoProfile -Command "Get-PnpDevice -PresentOnly | Where-Object { $_.Class -eq \'Bluetooth\' -and $_.FriendlyName -match \'HID|Keyboards\' } | Select-Object -ExpandProperty InstanceId"',
                "label": "No present Bluetooth HID adapter detected"}],
      updated="2026-09-27",
      tags=["bluetooth", "hid", "power"],),

])
