"""License database for the MAXIMUM TWEAKS license server.

SQLite by default, PostgreSQL (Neon) when ``DATABASE_URL`` is set.

* SQLite (no ``DATABASE_URL``): used for local development. Defaults to
  ``auth_backend/licenses.db`` (override with ``LICENSE_DB_PATH``).
* PostgreSQL (``DATABASE_URL`` set): used in production on Render/Neon so
  licenses survive restarts/redeploys without a persistent disk.

Both backends expose the same ``LicenseDB`` API; the licensing logic in
``main.py``/``keys.py`` is identical either way. The desktop app never touches
this store — it only ever talks to the HTTP API in ``main.py``.

Note on Postgres connections: we deliberately open a *fresh* connection per
operation instead of using a warm pool. ``psycopg_pool`` (as used previously)
strands its worker threads after a few getconn/putconn cycles and then times
out on every subsequent call — that surfaced as persistent ``HTTP 500``s on
the live license server. This store is low-traffic, so the ~10-500ms connect
overhead per operation is a fair price for never hanging again.

All times are UTC in ``YYYY-MM-DD HH:MM:SS`` strings (same format the old
Discord backend used). ``expires_at`` is NULL for lifetime licenses.
"""
from __future__ import annotations

import os
import sqlite3
import threading
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - only needed when DATABASE_URL is set
    psycopg = None
    dict_row = None

import logging
logger = logging.getLogger("maxtweaks.license.db")

DEFAULT_DB_PATH = Path(__file__).resolve().parent / "licenses.db"

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    license_key      TEXT    NOT NULL UNIQUE,
    status           TEXT    NOT NULL DEFAULT 'unused',   -- unused|active|revoked|expired
    plan             TEXT    NOT NULL DEFAULT 'lifetime', -- lifetime|monthly|yearly|custom
    customer         TEXT    NOT NULL DEFAULT '',
    note             TEXT    NOT NULL DEFAULT '',
    created_at       TEXT    NOT NULL,
    expires_at       TEXT    DEFAULT NULL,                -- NULL = lifetime
    activated_at     TEXT    DEFAULT NULL,
    device_id        TEXT    DEFAULT NULL,                -- hashed device fingerprint
    activation_count INTEGER NOT NULL DEFAULT 0,
    last_validated   TEXT    DEFAULT NULL,
    revoked_at       TEXT    DEFAULT NULL,
    revoked_reason   TEXT    NOT NULL DEFAULT '',
    reset_count      INTEGER NOT NULL DEFAULT 0           -- support unbinds (PC change)
);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status);

-- Per-PC check-in activity (heartbeat). One row per key+PC+day.
CREATE TABLE IF NOT EXISTS key_activity (
    license_key TEXT    NOT NULL,
    pc_hwid     TEXT    NOT NULL,
    day         TEXT    NOT NULL,          -- YYYY-MM-DD (UTC)
    pc_name     TEXT    NOT NULL DEFAULT '',
    seen_count  INTEGER NOT NULL DEFAULT 1,
    last_seen   TEXT    NOT NULL,
    PRIMARY KEY (license_key, pc_hwid, day)
);
CREATE INDEX IF NOT EXISTS idx_key_activity_key_day ON key_activity(license_key, day);
CREATE INDEX IF NOT EXISTS idx_key_activity_key_hwid ON key_activity(license_key, pc_hwid);

-- Logged refusals (e.g. a new PC trying to check in while the key is at its
-- PC limit, revoked, expired or unknown).
CREATE TABLE IF NOT EXISTS key_blocked (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    license_key TEXT    NOT NULL,
    pc_hwid     TEXT    NOT NULL,
    pc_name     TEXT    NOT NULL DEFAULT '',
    at          TEXT    NOT NULL,          -- UTC timestamp of the refused check-in
    reason      TEXT    NOT NULL DEFAULT 'over_limit'
);
CREATE INDEX IF NOT EXISTS idx_key_blocked_key_at ON key_blocked(license_key, at);
"""

PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS licenses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key      TEXT    NOT NULL UNIQUE,
    status           TEXT    NOT NULL DEFAULT 'unused',
    plan             TEXT    NOT NULL DEFAULT 'lifetime',
    customer         TEXT    NOT NULL DEFAULT '',
    note             TEXT    NOT NULL DEFAULT '',
    created_at       TEXT    NOT NULL,
    expires_at       TEXT    DEFAULT NULL,
    activated_at     TEXT    DEFAULT NULL,
    device_id        TEXT    DEFAULT NULL,
    activation_count INTEGER NOT NULL DEFAULT 0,
    last_validated   TEXT    DEFAULT NULL,
    revoked_at       TEXT    DEFAULT NULL,
    revoked_reason   TEXT    NOT NULL DEFAULT '',
    reset_count      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status);

CREATE TABLE IF NOT EXISTS key_activity (
    license_key TEXT    NOT NULL,
    pc_hwid     TEXT    NOT NULL,
    day         TEXT    NOT NULL,
    pc_name     TEXT    NOT NULL DEFAULT '',
    seen_count  INTEGER NOT NULL DEFAULT 1,
    last_seen   TEXT    NOT NULL,
    PRIMARY KEY (license_key, pc_hwid, day)
);
CREATE INDEX IF NOT EXISTS idx_key_activity_key_day ON key_activity(license_key, day);
CREATE INDEX IF NOT EXISTS idx_key_activity_key_hwid ON key_activity(license_key, pc_hwid);

CREATE TABLE IF NOT EXISTS key_blocked (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key TEXT    NOT NULL,
    pc_hwid     TEXT    NOT NULL,
    pc_name     TEXT    NOT NULL DEFAULT '',
    at          TEXT    NOT NULL,
    reason      TEXT    NOT NULL DEFAULT 'over_limit'
);
CREATE INDEX IF NOT EXISTS idx_key_blocked_key_at ON key_blocked(license_key, at);
"""


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def _utc_day(offset: int = 0) -> str:
    """UTC date string 'YYYY-MM-DD', offset days back from today (negative = past)."""
    return (datetime.now(timezone.utc) + timedelta(days=offset)).strftime("%Y-%m-%d")


def _utc_ts(offset_minutes: int = 0) -> str:
    """Full UTC timestamp, offset minutes back from now (negative = past)."""
    return (datetime.now(timezone.utc) + timedelta(minutes=offset_minutes)).strftime("%Y-%m-%d %H:%M:%S")


def _is_expired(expires_at: str | None) -> bool:
    if not expires_at:
        return False
    try:
        exp = datetime.strptime(expires_at, "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
    except ValueError:
        return False
    return exp.timestamp() <= time.time()


def _parse_db_path() -> str:
    override = os.environ.get("LICENSE_DB_PATH", "").strip()
    if override:
        return override
    return str(DEFAULT_DB_PATH)


class LicenseDB:
    """Thread-safe license store: SQLite locally, PostgreSQL when DATABASE_URL
    is set. The public API is identical for both backends."""

    def __init__(self, path: str | None = None):
        self._dsn = os.environ.get("DATABASE_URL", "").strip() or None
        self._engine = "postgres" if self._dsn else "sqlite"
        self._path = path or _parse_db_path()
        if self._engine == "sqlite":
            os.makedirs(os.path.dirname(self._path) or ".", exist_ok=True)
        self._lock = threading.RLock()
        with self._lock:
            conn = self._connect()
            try:
                self._init_schema(conn)
                conn.commit()
            finally:
                conn.close()

    @property
    def engine(self) -> str:
        """'postgres' when DATABASE_URL is set, else 'sqlite'."""
        return self._engine

    def _connect(self):
        if self._engine == "postgres":
            if psycopg is None:  # pragma: no cover
                raise RuntimeError(
                    "DATABASE_URL is set but psycopg is not installed - "
                    "run: pip install -r requirements.txt")
            # A fresh, dedicated connection per operation. See the module
            # docstring for why we don't pool here: psycopg_pool strands its
            # worker threads after a few cycles and then times out on every
            # subsequent call (which is what made the live server return HTTP
            # 500s on every database route).
            return psycopg.connect(self._dsn, connect_timeout=15,
                                   row_factory=dict_row)
        conn = sqlite3.connect(self._path, timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA busy_timeout = 30000")
        return conn

    def _init_schema(self, conn) -> None:
        if self._engine == "postgres":
            for stmt in PG_SCHEMA.split(";"):
                stmt = stmt.strip()
                if stmt:
                    conn.execute(stmt)
        else:
            conn.executescript(SQLITE_SCHEMA)
        self._migrate_columns(conn)

    _NEW_COLUMNS = (
        ("max_pcs", "INTEGER NOT NULL DEFAULT 1"),
        ("pc_name", "TEXT NOT NULL DEFAULT ''"),
        ("last_seen", "TEXT DEFAULT NULL"),
    )

    def _migrate_columns(self, conn) -> None:
        """Idempotently add columns introduced after the first deploy."""
        def _existing():
            if self._engine == "postgres":
                rows = conn.execute(
                    "SELECT column_name FROM information_schema.columns"
                    " WHERE table_name = 'licenses'").fetchall()
                return {r["column_name"] for r in rows}
            rows = conn.execute("PRAGMA table_info(licenses)").fetchall()
            return {r["name"] for r in rows}
        try:
            existing = _existing()
            for name, ddl in self._NEW_COLUMNS:
                if name not in existing:
                    conn.execute(f"ALTER TABLE licenses ADD COLUMN {name} {ddl}")
        except Exception:  # noqa: BLE001 - tolerate weird schemas in tests
            logger.warning("db: column migration skipped", exc_info=True)

    def _sql(self, q: str) -> str:
        """Rewrite SQLite '?' placeholders to psycopg '%s' for Postgres."""
        if self._engine == "postgres":
            return q.replace("?", "%s")
        return q

    @staticmethod
    def _is_stale_conn(exc) -> bool:
        """True when the error indicates a dead/purged pooled connection."""
        msg = str(exc).lower()
        return any(s in msg for s in (
            "adminshutdown", "server closed", "connection attempt failed",
            "connection already closed", "could not connect",
        ))

    def _exec(self, conn, sql: str, params=()):
        """Run one statement with engine-appropriate placeholders."""
        if params:
            return conn.execute(self._sql(sql), params)
        return conn.execute(self._sql(sql))

    def _run_with_retry(self, fn, *, commit: bool = True):
        """Execute *fn(conn)* with a fresh connection; retry once on stale/
        transient errors (each attempt dials a brand-new connection)."""
        for attempt in range(2):
            conn = self._connect()
            try:
                result = fn(conn)
                if commit:
                    conn.commit()
                return result
            except Exception as exc:
                try:
                    conn.close()
                except Exception:  # noqa: BLE001
                    pass
                if attempt == 0 and self._is_stale_conn(exc):
                    logger.warning("db: stale/transient connection, retrying "
                                   "(attempt %d)", attempt + 1)
                    continue
                raise
            else:
                try:
                    conn.close()
                except Exception:  # noqa: BLE001
                    pass

    # ------------------------------------------------------------------
    # Row helpers
    # ------------------------------------------------------------------

    def _row_to_dict(self, row) -> dict | None:
        if row is None:
            return None
        return {key: row[key] for key in row.keys()}

    def get(self, license_key: str) -> dict | None:
        def _fn(conn):
            row = self._exec(
                conn, "SELECT * FROM licenses WHERE license_key = ?",
                (license_key,)).fetchone()
            return self._row_to_dict(row)
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    # ------------------------------------------------------------------
    # Writes (admin + activation flow)
    # ------------------------------------------------------------------

    def create(self, license_key: str, plan: str = "lifetime",
               customer: str = "", note: str = "",
               expires_at: str | None = None,
               max_pcs: int = 1) -> dict:
        def _fn(conn):
            self._exec(
                conn,
                "INSERT INTO licenses (license_key, status, plan, customer,"
                " note, created_at, expires_at, max_pcs)"
                " VALUES (?, 'unused', ?, ?, ?, ?, ?, ?)",
                (license_key, plan, customer, note, _utc_now(), expires_at, max_pcs))
        with self._lock:
            self._run_with_retry(_fn)
        rec = self.get(license_key)
        if rec is None:  # pragma: no cover
            raise RuntimeError("license record was not created")
        return rec

    def activate(self, license_key: str, device_id: str) -> dict:
        """Bind an unused license to a device and mark it active."""
        now = _utc_now()
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'active', device_id = ?,"
                " activated_at = COALESCE(activated_at, ?),"
                " activation_count = activation_count + 1,"
                " last_validated = ?, revoked_at = NULL,"
                " revoked_reason = '' WHERE license_key = ?",
                (device_id, now, now, license_key))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def touch_validation(self, license_key: str) -> None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET last_validated = ? WHERE license_key = ?",
                (_utc_now(), license_key))
        with self._lock:
            self._run_with_retry(_fn)

    def mark_expired(self, license_key: str) -> None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'expired' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)

    def revoke(self, license_key: str, reason: str = "") -> dict | None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'revoked', revoked_at = ?,"
                " revoked_reason = ? WHERE license_key = ?",
                (_utc_now(), reason, license_key))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def unrevoke(self, license_key: str) -> dict | None:
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'active', revoked_at = NULL,"
                " revoked_reason = '' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def unbind(self, license_key: str) -> dict | None:
        """Support action for a PC change: unbind the device and free the key."""
        def _fn(conn):
            self._exec(
                conn,
                "UPDATE licenses SET status = 'unused', device_id = NULL,"
                " activated_at = NULL, reset_count = reset_count + 1,"
                " revoked_at = NULL, revoked_reason = '' WHERE license_key = ?",
                (license_key,))
        with self._lock:
            self._run_with_retry(_fn)
        return self.get(license_key)

    def delete(self, license_key: str) -> int:
        """Permanently remove a key row. Admin-ops only. Returns rows deleted."""
        def _fn(conn):
            cur = self._exec(
                conn,
                "DELETE FROM licenses WHERE license_key = ?",
                (license_key,))
            return cur.rowcount
        with self._lock:
            n = self._run_with_retry(_fn)
        return n if n is not None else 0

    def list_all(self, status: str | None = None) -> list[dict]:
        def _fn(conn):
            if status:
                rows = self._exec(
                    conn,
                    "SELECT * FROM licenses WHERE status = ?"
                    " ORDER BY created_at DESC", (status,)).fetchall()
            else:
                rows = self._exec(
                    conn,
                    "SELECT * FROM licenses ORDER BY created_at DESC").fetchall()
            return [self._row_to_dict(r) for r in rows]
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    def search(self, q: str) -> list[dict]:
        """Admin search across license key / customer / note (substring)."""
        def _fn(conn):
            like = f"%{q}%"
            rows = self._exec(
                conn,
                "SELECT * FROM licenses WHERE license_key LIKE ?"
                " OR customer LIKE ? OR note LIKE ?"
                " ORDER BY created_at DESC",
                (like, like, like)).fetchall()
            return [self._row_to_dict(r) for r in rows]
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    def stats(self) -> dict:
        def _fn(conn):
            rows = self._exec(
                conn,
                "SELECT status, COUNT(*) AS n FROM licenses GROUP BY status").fetchall()
            total = self._exec(
                conn,
                "SELECT COUNT(*) AS n FROM licenses").fetchone()["n"]
            return {"total": total, "by_status": {r["status"]: r["n"] for r in rows}}
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    # ------------------------------------------------------------------
    # Check-in (heartbeat) flow
    # ------------------------------------------------------------------

    def checkin(self, license_key: str, hwid: str, pc_name: str = "") -> dict:
        """Handle a heartbeat check-in from the customer app.

        Returns:
          allowed  -> {"status": "allowed", "expires_at": ..., "plan": ...}
          refused  -> {"status": "refused", "error": <code>, "message": ...}
          * "invalid_license" - unknown key
          * "license_revoked" - revoked
          * "license_expired" - past expiry
          * "over_limit"      - already at max_pcs active PCs (very rare:
            because the day-window frees old PCs, this can only trigger when
            more PCs check in within the window than the limit allows)
        """
        def _fn(conn):
            row = self._exec(
                conn, "SELECT * FROM licenses WHERE license_key = ?",
                (license_key,)).fetchone()
            rec = self._row_to_dict(row)
            if rec is None:
                return {"status": "refused", "error": "invalid_license",
                        "message": "That license key wasn't recognized."}
            if rec["status"] == "revoked":
                return {"status": "refused", "error": "license_revoked",
                        "message": ("This license key has been revoked. "
                                    "Contact support to re-activate it.")}
            if _is_expired(rec["expires_at"]):
                self._exec(conn, "UPDATE licenses SET status = 'expired'"
                           " WHERE license_key = ?", (license_key,))
                return {"status": "refused", "error": "license_expired",
                        "message": "This license key has expired."}

            max_pcs = int(rec.get("max_pcs") or 1)
            exp = rec.get("expires_at")
            plan = rec.get("plan")

            # Active set = distinct PCs that checked in within the last 30
            # days. A PC drops out of this window automatically after 30 days
            # of silence, which frees its slot without a manual unbind.
            active_rows = self._exec(
                conn,
                "SELECT DISTINCT pc_hwid FROM key_activity"
                " WHERE license_key = ? AND day >= ?",
                (license_key, _utc_day(-29))).fetchall()
            active_hwids = {r["pc_hwid"] for r in active_rows}

            if hwid in active_hwids:
                self._upsert_activity(conn, license_key, hwid, pc_name)
                return {"status": "allowed", "expires_at": exp, "plan": plan}

            if len(active_hwids) >= max_pcs:
                # New PC beyond the limit: refuse it (and keep the existing
                # PCs working). Log it so the admin panel can show "X blocked
                # attempts this week".
                self._exec(
                    conn,
                    "INSERT INTO key_blocked (license_key, pc_hwid, pc_name,"
                    " at, reason) VALUES (?, ?, ?, ?, 'over_limit')",
                    (license_key, hwid, pc_name, _utc_now()))
                return {"status": "refused", "error": "over_limit",
                        "message": ("This key is already used on the maximum "
                                    "number of PCs.")}

            self._upsert_activity(conn, license_key, hwid, pc_name)
            return {"status": "allowed", "expires_at": exp, "plan": plan}

        with self._lock:
            return self._run_with_retry(_fn)

    def _upsert_activity(self, conn, license_key: str, hwid: str,
                         pc_name: str) -> None:
        now = _utc_now()
        self._exec(
            conn,
            "INSERT INTO key_activity (license_key, pc_hwid, day, pc_name,"
            " seen_count, last_seen) VALUES (?, ?, ?, ?, 1, ?)"
            " ON CONFLICT (license_key, pc_hwid, day) DO UPDATE SET"
            " pc_name = excluded.pc_name,"
            " seen_count = key_activity.seen_count + 1,"
            " last_seen = excluded.last_seen",
            (license_key, hwid, _utc_day(), pc_name, now))
        # Also refresh the license-level last_seen / current pc_name so the
        # admin list can show "Last check-in" per key at a glance.
        self._exec(
            conn,
            "UPDATE licenses SET last_seen = ?, pc_name = ?"
            " WHERE license_key = ?",
            (now, pc_name, license_key))

    # ------------------------------------------------------------------
    # Activity reads (admin)
    # ------------------------------------------------------------------

    def activity(self, license_key: str, days: int = 30) -> dict:
        """Per-PC check-in grid for the key detail panel plus recent refusals."""
        def _fn(conn):
            rows = self._exec(
                conn,
                "SELECT pc_hwid, pc_name, day, last_seen FROM key_activity"
                " WHERE license_key = ? AND day >= ? ORDER BY pc_hwid, day",
                (license_key, _utc_day(-(days - 1)))).fetchall()
            blocked = self._exec(
                conn,
                "SELECT pc_hwid, pc_name, at, reason FROM key_blocked"
                " WHERE license_key = ? AND at >= ? ORDER BY at DESC LIMIT 50",
                (license_key, _utc_ts(-(7 * 24 * 60)))).fetchall()
            pcs: dict[str, dict] = {}
            for r in rows:
                pc = pcs.setdefault(r["pc_hwid"], {
                    "hwid": r["pc_hwid"], "name": r["pc_name"],
                    "last_seen": r["last_seen"], "days": {}})
                pc["days"][r["day"]] = True
                if pc["name"] != r["pc_name"] and r["pc_name"]:
                    pc["name"] = r["pc_name"]
            return {
                "pcs": [p for p in pcs.values()],
                "blocked": [dict(r) for r in blocked],
            }
        with self._lock:
            return self._run_with_retry(_fn, commit=False)

    def remove_pc(self, license_key: str, hwid: str) -> int:
        """Drop a PC from a key so its slot is freed immediately. Admin-ops."""
        def _fn(conn):
            cur = self._exec(
                conn, "DELETE FROM key_activity WHERE license_key = ?"
                " AND pc_hwid = ?", (license_key, hwid))
            return cur.rowcount
        with self._lock:
            n = self._run_with_retry(_fn)
        return n if n is not None else 0

    def overview(self) -> dict:
        """Everything the admin panel needs for the key list + stats cards, in
        a handful of whole-table queries (no per-key N+1)."""
        def _fn(conn):
            keys = [self._row_to_dict(r) for r in self._exec(
                conn, "SELECT * FROM licenses ORDER BY created_at DESC").fetchall()]

            day_rows = [dict(r) for r in self._exec(
                conn,
                "SELECT license_key, day, COUNT(DISTINCT pc_hwid) AS n"
                " FROM key_activity WHERE day >= ? GROUP BY license_key, day",
                (_utc_day(-29),)).fetchall()]
            day_counts: dict[str, dict] = {}
            for r in day_rows:
                day_counts.setdefault(r["license_key"], {})[r["day"]] = r["n"]

            pc_rows = [dict(r) for r in self._exec(
                conn,
                "SELECT license_key, pc_hwid, MAX(pc_name) AS pc_name,"
                " MAX(last_seen) AS last_seen FROM key_activity WHERE day >= ?"
                " GROUP BY license_key, pc_hwid",
                (_utc_day(-29),)).fetchall()]
            pcs: dict[str, list[dict]] = {}
            for r in pc_rows:
                pcs.setdefault(r["license_key"], []).append({
                    "hwid": r["pc_hwid"], "name": r["pc_name"],
                    "last_seen": r["last_seen"]})

            blocked = [dict(r) for r in self._exec(
                conn,
                "SELECT license_key, COUNT(*) AS n FROM key_blocked"
                " WHERE at >= ? GROUP BY license_key",
                (_utc_ts(-(7 * 24 * 60)),)).fetchall()]
            blocked_week: dict[str, int] = {r["license_key"]: r["n"] for r in blocked}

            return {
                "keys": [
                    {
                        **k,
                        "pcs": pcs.get(k["license_key"], []),
                        "day_counts": day_counts.get(k["license_key"], {}),
                        "blocked_week": blocked_week.get(k["license_key"], 0),
                    }
                    for k in keys
                ],
                "day_counts": day_counts,
                "pcs": pcs,
                "blocked_week": blocked_week,
            }
        with self._lock:
            return self._run_with_retry(_fn, commit=False)
