"""Permanent record of tweaks removed from the shipped catalogue.

Auto-generated consolidation log: these entries were removed on 2026-10-02 as
part of the classification audit (see _dev/audit_gen.py and docs/tweak_audit.md).
They are kept so the reason for each removal stays reviewable long after the
tweak itself is gone from the modules. Nothing here is loaded into BY_ID; this
file exists purely for history.

The 2026-10-08 final-release audit removed a second batch (see the block at
the end of REMOVED_TWEAKS): duplicate consolidation to strictly-exactly-once,
plus the svc-001 REWRITE resolution.

Each record carries:
  * the canonical tweak that still ships the same (target, value) pair, when
    the removal was a duplicate consolidation (``canonical`` is not None);
  * or the hazard that made the tweak unsafe to ship (``canonical`` is None).
"""
from __future__ import annotations

#: id -> {name, reason, canonical}.  ``canonical`` is the kept twin for exact
#: duplicates; None means the tweak was removed for being unsafe/stale.
REMOVED_TWEAKS: dict[str, dict[str, str | None]] = {
    "exp-008": {"name": "Disable XAML Activity Feed",
                "reason": "Exact duplicate of `tel-004` (same target and value); tel-004 ships instead.",
                "canonical": "tel-004"},
    "fpsb-007": {"name": "Disable Background Apps",
                 "reason": "Exact duplicate of `lap-044` (same target and value); lap-044 ships instead.",
                 "canonical": "lap-044"},
    "fpsb-011": {"name": "Activate Maximum Power Plan",
                 "reason": "Exact duplicate of `pp-013` (same target and value); pp-013 ships instead.",
                 "canonical": "pp-013"},
    "fpsb-013": {"name": "Minimize System Responsiveness Reserve",
                 "reason": "Exact duplicate of `pre-006` (same target and value); pre-006 ships instead.",
                 "canonical": "pre-006"},
    "fpsb-024": {"name": "Disable Toast Notifications",
                 "reason": "Exact duplicate of `perf-012` (same target and value); perf-012 ships instead.",
                 "canonical": "perf-012"},
    "lap-015": {"name": "Disable Modern Standby",
                "reason": "Exact duplicate of `power-027` (same target and value); power-027 ships instead.",
                "canonical": "power-027"},
    "lap-031": {"name": "Prevent Display Sleep on Dock",
                "reason": "Exact duplicate of `reg-001` (same target and value); reg-001 ships instead.",
                "canonical": "reg-001"},
    "mouse-001": {"name": "Disable Mouse Acceleration",
                  "reason": "Exact duplicate of `il-007` (same target and value); il-007 ships instead.",
                  "canonical": "il-007"},
    "perf-006": {"name": "Disable Page Combining",
                 "reason": "Exact duplicate of `perf-043` (same target and value); perf-043 ships instead.",
                 "canonical": "perf-043"},
    "perf-010": {"name": "Disable Unnecessary Visual Effects",
                 "reason": "Exact duplicate of `win-006` (same target and value); win-006 ships instead.",
                 "canonical": "win-006"},
    "perf-026": {"name": "Disable Power Throttling",
                 "reason": "Exact duplicate of `power-021` (same target and value); power-021 ships instead.",
                 "canonical": "power-021"},
    "perf-032": {"name": "Set Win32PrioritySeparation",
                 "reason": "Exact duplicate of `adv-006` (same target and value); adv-006 ships instead.",
                 "canonical": "adv-006"},
    "perf-044": {"name": "Disable MMCSS Network Throttling",
                 "reason": "Exact duplicate of `net-009` (same target and value); net-009 ships instead.",
                 "canonical": "net-009"},
    "perf-045": {"name": "Optimize MMCSS SystemResponsiveness",
                 "reason": "Exact duplicate of `pre-006` (same target and value); pre-006 ships instead.",
                 "canonical": "pre-006"},
    "pre-002": {"name": "Fire Timing",
                "reason": "Exact duplicate of `pre-006` (same target and value); pre-006 ships instead.",
                "canonical": "pre-006"},
    "wgr-007": {"name": "NVIDIA Maximum Performance Global",
                "reason": "Targets a registry key or mechanism that does not exist on supported Windows; unsafe/stale, not relabelled to preserve the count.",
                "canonical": None},
    "win-011": {"name": "Disable Automatic Windows Update",
                "reason": "Disables Windows Update wholesale (NoAutoUpdate=1); unsafe to ship. Update-management optimisation, if ever wanted, must be a separate properly supported tweak.",
                "canonical": None},
    "adv-004": {"name": 'Disable Auto-Logging Metadata',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "adv-010": {"name": 'Disable Indexing of Game Drives',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "adv-011": {"name": 'Disable Busy Wait Timer',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-001": {"name": 'Enable Radeon Anti-Lag',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-002": {"name": 'Enable Radeon Chill',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-003": {"name": 'Image Sharpening Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-004": {"name": 'Disable FreeSync if Stuttering',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-005": {"name": 'Driver Update via AMD Software',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-006": {"name": 'Disable Radeon Overlay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-007": {"name": 'Smart Access Memory Check',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-008": {"name": 'Radeon Boost Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-009": {"name": 'Surface Format Optimization',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-010": {"name": 'Tessellation Level Cap',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-011": {"name": 'Shader Cache Management',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-012": {"name": 'Disable Background Recording',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-013": {"name": 'Reset AMD Software Settings',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-014": {"name": 'Radeon Super Resolution',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-015": {"name": 'Texture Filtering Quality - Performance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-016": {"name": 'Enhanced Sync',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "amd-017": {"name": 'Frame Rate Target Control (FRTC)',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-009": {"name": 'Set 48 kHz Default Format',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-010": {"name": 'Disable Audio Device Power Savings',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-016": {"name": 'Disable Audio Processing Objects (APO)',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-021": {"name": 'Disable USB Enhanced Power Management',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-022": {"name": 'Disable USB Audio Remote Wakeup',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-031": {"name": 'Disable Microphone Boost',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-035": {"name": 'Disable Audio Power Management (Laptop)',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-037": {"name": 'LatencyMon DPC Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-038": {"name": 'Gaming Audio Preset',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-039": {"name": 'Voice Chat Preset',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-040": {"name": 'USB Headset Preset',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "audio-041": {"name": 'DAC / Audio Interface Preset',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "bg-003": {"name": 'Pause Windows Update During Play',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "bg-004": {"name": 'Disable Background Printing',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "bg-006": {"name": 'Disable Cloud Sync for Game Folders',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "db-012": {"name": 'Remove Third-Party Pre-Installed Bloat',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "disp-006": {"name": 'Primary Monitor Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "disp-007": {"name": 'Display Scaling Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "disp-008": {"name": 'Preferred Refresh for Games',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "disp-010": {"name": 'Enable G-SYNC in Windowed Mode',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "disp-011": {"name": 'Reset Display Driver',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-002": {"name": 'Update DirectX Runtime',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-004": {"name": 'Verify Feature Level in Games',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-005": {"name": 'Shader Compilation Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-006": {"name": 'Async Compute Note',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-007": {"name": 'Ray Tracing Overhead Note',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-008": {"name": 'Mesh Shader Note',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-009": {"name": 'D3D9 Windowed Optimizations',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx-010": {"name": 'Update GPU Drivers for DX12',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-002": {"name": 'DirectStorage Enable',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-003": {"name": 'Reduce CPU Overhead',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-004": {"name": 'Shader Caching for DX12',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-005": {"name": 'Work Graphs Note',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-006": {"name": 'Resource Binding Tier Check',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-007": {"name": 'DXR Ray Tracing Tuning',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-008": {"name": 'Sampler Feedback Note',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-009": {"name": 'Force DX12 in Supported Games',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "dx12-010": {"name": 'Keep DX12 Memory Headroom',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "exp-006": {"name": 'Enable Undocumented GPU Tweaks',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "exp-007": {"name": 'Enable Variable Refresh Overscan Fix',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "exp-009": {"name": 'Disable Virtualization for Games',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "exp-010": {"name": 'Enable Direct Storage on Older GPUs',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-001": {"name": 'Use Performance Mode',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-002": {"name": 'Cap FPS to Refresh',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-003": {"name": 'Enable Reflex',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-004": {"name": 'Lobby FPS Cap',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-005": {"name": 'Optimize View Distance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-006": {"name": 'Shadow and Effects Off',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-007": {"name": 'Use Epic Launcher Offline Mode',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-008": {"name": 'Verify Fortnite Files',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-009": {"name": 'Disable HDR in Fortnite',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fn-010": {"name": 'Latency Network Settings',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-001": {"name": 'Uncap FPS in Game',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-002": {"name": 'Reduce Render Resolution',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-003": {"name": 'Disable Anti-Aliasing Overrides',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-004": {"name": 'Disable Volumetric Effects',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-005": {"name": 'Disable Ray Tracing',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-006": {"name": 'Lower Shadow Quality',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-007": {"name": 'Disable Motion Blur',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-008": {"name": 'Lower Texture Pool Within VRAM',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-009": {"name": 'Use Per-Game Benchmark',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-010": {"name": 'Close Background Encoders',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-011": {"name": 'Lower CPU-Bound Settings',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fps-012": {"name": 'Set Fixed Refresh in Drivers',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fpsb-004": {"name": 'NVIDIA Power Management (Vendor Guidance)',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "fpsb-016": {"name": 'Enable Windows Game Mode',
                "reason": 'Duplicate/merged entry consolidated into `perf-002`; the kept tweak ships the same setting.',
                "canonical": 'perf-002'},
    "fpsb-023": {"name": 'Disable Windows Telemetry',
                "reason": 'Duplicate/merged entry consolidated into `ram-030`; the kept tweak ships the same setting.',
                "canonical": 'ram-030'},
    "ft-001": {"name": 'Measure 1% Lows',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-002": {"name": 'Cap Frame Rate for Consistency',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-003": {"name": 'Disable Scheduler Jitter',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-004": {"name": 'Check DPC Latency',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-005": {"name": 'Update Chipset Drivers',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-006": {"name": 'Disable Third-Party Anti-Cheat Overhead',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-007": {"name": 'Reduce USB Device Count',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-008": {"name": 'Check Thermal Throttling',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-009": {"name": 'Run Game on Same Disk as Windows',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-010": {"name": 'Disable Browser Hardware Acceleration',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-011": {"name": 'Test Frame Time After Each Tweak',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ft-012": {"name": 'Prefer Dedicated GPU in Laptops',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-004": {"name": 'Install Gaming Features',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-005": {"name": 'Set Game Client Priorities',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-007": {"name": 'Enable Hardware-Accelerated Video in Games',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-008": {"name": 'Close Launchers After Start',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-009": {"name": 'Disable Discord/Steam In-Game Overlay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-010": {"name": 'Disable Auto Game Saves Syncing',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-011": {"name": 'Verify Game File Integrity',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-012": {"name": 'Game Folder on SSD',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-013": {"name": 'Keep Graphics Drivers Current for New Titles',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-014": {"name": 'Run Game on Dedicated GPU',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-015": {"name": 'Disable OneDrive During Play',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "game-016": {"name": 'Enable Game Overlay for Recording Only',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-001": {"name": 'Fortnite Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-002": {"name": 'Valorant Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-003": {"name": 'Counter-Strike 2 Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-004": {"name": 'Call of Duty Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-005": {"name": 'Apex Legends Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-006": {"name": 'Overwatch 2 Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-007": {"name": 'Minecraft Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-008": {"name": 'Rocket League Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-009": {"name": 'League of Legends Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-010": {"name": 'Rust Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-011": {"name": 'Escape from Tarkov Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gp-012": {"name": 'Warzone Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-005": {"name": 'Prefer Native Resolution',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-006": {"name": 'Disable Background GPU Apps',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-007": {"name": 'Clear Stale GPU Cache',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-008": {"name": 'Enable GPU Video Decoding',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-009": {"name": 'Set Frame Rate Target',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-010": {"name": 'Avoid Driver Overclocks',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-011": {"name": 'Monitor GPU Hotspot',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-012": {"name": 'Turn Off VSync',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-013": {"name": 'Use Reflex/LLM/ULMB Aware Settings',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-014": {"name": 'Check PCIe Lane Width',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-015": {"name": 'Disable Fullscreen Scaled View',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "gpu-016": {"name": 'Run GPU Benchmark',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "il-005": {"name": 'Set Mouse Precision Mode',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "il-008": {"name": 'Enable Raw Mouse Rate',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "il-012": {"name": 'Disable Pointer Acceleration in Games Config',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-001": {"name": 'Disable Intel Gaming Overlay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-002": {"name": 'Enable Resizable BAR',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-004": {"name": 'Prefer Performance Mode',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-005": {"name": 'Driver Update Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-006": {"name": 'Enable Adaptive Sync',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-007": {"name": 'Shader Cache Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-008": {"name": 'XeSS Upscaling Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-010": {"name": 'Check Forced Max FPS',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-011": {"name": 'Hybrid Graphics GPU Selection',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "int-012": {"name": 'Fix Dual-GPU Tearing',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-008": {"name": 'Gaming Keyboard Polling Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-009": {"name": 'Disable Key Remap Software',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-010": {"name": 'Disable Caps Lock Accidental Toggle',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-011": {"name": 'Fast Key Repeat Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-012": {"name": 'Update Keyboard Driver',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-013": {"name": 'Keyboard Input Boost (MMCSS)',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-036": {"name": 'No USB Keyboard Selective Suspend',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-037": {"name": 'Keyboard Never Powers Off',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-038": {"name": 'No HID Selective Suspend',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-039": {"name": 'HID Devices Never Power Off',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-040": {"name": 'Keyboard MMCSS GPU Priority',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-041": {"name": 'Keyboard MMCSS SFIO Priority',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-042": {"name": 'Keyboard MMCSS Background Only Off',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "kbd-043": {"name": 'Disable Touch Keyboard Service',
                "reason": 'Duplicate/merged entry consolidated into `svc-012`; the kept tweak ships the same setting.',
                "canonical": 'svc-012'},
    "kbd-044": {"name": 'Disable Bluetooth for Wired Input',
                "reason": 'Duplicate/merged entry consolidated into `svc-010`; the kept tweak ships the same setting.',
                "canonical": 'svc-010'},
    "lap-028": {"name": 'Battery Charge Limit Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-004": {"name": 'High Refresh Rate Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-005": {"name": 'Response Time Overdrive',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-007": {"name": 'Disable HDR Auto-Toggle',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-008": {"name": 'GSYNC/FreeSync Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-009": {"name": 'Disable Monitor Off During Streaming',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-010": {"name": 'Resolution Scaling Check',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-011": {"name": 'Disable Night Light Scheduler',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-012": {"name": 'Monitor Firmware/Driver Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mon-013": {"name": "Disable 'Hide Display Timeout' in Games",
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mouse-005": {"name": 'Default Pointer Curves',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mouse-006": {"name": 'Mouse DPI Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mouse-007": {"name": 'Mouse Polling Rate Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mouse-008": {"name": 'Raw Input for FPS',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "mouse-012": {"name": 'USB Mouse Power Saving',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-003": {"name": 'Enable PowerMizer',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-005": {"name": 'Disable NVIDIA Telemetry Service',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-007": {"name": 'Low Latency Mode Ultra',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-009": {"name": 'G-SYNC Compatibility Check',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-010": {"name": 'Disable DSR',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-011": {"name": 'Threaded Optimization Auto',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-012": {"name": 'Max Pre-Rendered Frames 1',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-013": {"name": 'Driver Update Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-014": {"name": 'Disable Ansel',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-015": {"name": 'Reflex Low Latency Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-019": {"name": 'Power Management Mode - Prefer Maximum Performance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-020": {"name": 'Shader Cache Size - Driver Default',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "nv-021": {"name": 'Texture Filtering Quality - High Performance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "perf-020": {"name": 'Enable MSI Mode for GPU',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "perf-051": {"name": 'Merged DirectX flag tweak (merged into wgr-013)',
                "reason": 'Duplicate/merged entry consolidated into `wgr-013`; the kept tweak ships the same setting.',
                "canonical": 'wgr-013'},
    "power-008": {"name": 'Disable Processor Idle State Control',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "power-012": {"name": 'Disable Power Throttling',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "power-013": {"name": 'Disable Connected Standby',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "power-014": {"name": 'Disable USB Idle Power Management',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "power-020": {"name": 'Disable Device Power Saving',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "pre-008": {"name": 'Stick Sync',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "priv-012": {"name": 'Disable App Sync',
                "reason": 'Duplicate/merged entry consolidated into `bg-008`; the kept tweak ships the same setting.',
                "canonical": 'bg-008'},
    "ram-007": {"name": 'Pagefile Placement Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-010": {"name": 'RAM Disk for Temp Files',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-011": {"name": 'Enable XMP/DOCP/EXPO Profile',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-013": {"name": 'Dual-Channel Verification',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-015": {"name": 'Clear Standby Memory List',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-016": {"name": 'Disable Large Page Pool Waste',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-017": {"name": 'Second-Level Cache Hint',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "ram-029": {"name": 'Disable Windows Search Indexing',
                "reason": 'Duplicate/merged entry consolidated into `svc-002`; the kept tweak ships the same setting.',
                "canonical": 'svc-002'},
    "ram-037": {"name": 'Disable Fax Service',
                "reason": 'Duplicate/merged entry consolidated into `svc-011`; the kept tweak ships the same setting.',
                "canonical": 'svc-011'},
    "ram-045": {"name": 'Disable Tablet Input Service',
                "reason": 'Duplicate/merged entry consolidated into `svc-012`; the kept tweak ships the same setting.',
                "canonical": 'svc-012'},
    "ram-055": {"name": 'Disable Print Spooler',
                "reason": 'Duplicate/merged entry consolidated into `svc-006`; the kept tweak ships the same setting.',
                "canonical": 'svc-006'},
    "rep-006": {"name": 'Repair Boot Records',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "rep-010": {"name": 'Windows Update Troubleshooter',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "rep-011": {"name": 'Startup Repair Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "rep-012": {"name": 'Reinstall Windows via Cloud',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-003": {"name": 'Disable Real-Time Protection While Gaming',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-004": {"name": 'Keep Windows Defender Enabled',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-005": {"name": 'Disable Windows Defender Tamper Delay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-006": {"name": 'Enable User Account Control',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-007": {"name": 'Run as Administrator for Tweak Tools',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sec-012": {"name": 'Disable Diagnostic Data',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-002": {"name": 'Disable Unused Startup Apps',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-006": {"name": 'Disable Boot Optimization Delay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-007": {"name": 'Disable Startup Repair Poll',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-008": {"name": 'Set BIOS Boot Order',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-009": {"name": 'Disable Third-Party Services',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-010": {"name": 'Reboot After Major Tweaks',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-011": {"name": 'Clean Temporary Boot Files',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-013": {"name": 'Preload Game on Dedicated GPU',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "start-014": {"name": 'Disable Automatic Startup of Update Tools',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "stor-013": {"name": 'Game Folder Compression Warning',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "stor-014": {"name": 'Move Games to Fastest Drive',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "svc-014": {"name": 'Disable Desktop Window Manager Session',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sys-011": {"name": 'Pagefile Sizing Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "sys-023": {"name": 'Optimize Active Hours',
                "reason": 'Duplicate/merged entry consolidated into `bg-010`; the kept tweak ships the same setting.',
                "canonical": 'bg-010'},
    "tel-001": {"name": 'Set Telemetry to Security',
                "reason": 'Duplicate/merged entry consolidated into `tel-009`; the kept tweak ships the same setting.',
                "canonical": 'tel-009'},
    "tel-011": {"name": 'Disable Sign-in Telemetry',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "usb-005": {"name": 'USB Polling Rate Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "usb-007": {"name": 'USB 3.x Driver Guidance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "usb-008": {"name": 'Legacy USB in BIOS',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "usb-010": {"name": 'Reset USB Stack',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wgr-001": {"name": 'Merged DirectX flag tweak (merged into wgr-013)',
                "reason": 'Duplicate/merged entry consolidated into `wgr-013`; the kept tweak ships the same setting.',
                "canonical": 'wgr-013'},
    "wgr-004": {"name": 'Merged DirectX flag tweak (merged into wgr-013)',
                "reason": 'Duplicate/merged entry consolidated into `wgr-013`; the kept tweak ships the same setting.',
                "canonical": 'wgr-013'},
    "wgr-005": {"name": 'Graphics Preference App List',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wgr-008": {"name": 'Merged DirectX flag tweak (merged into wgr-013)',
                "reason": 'Duplicate/merged entry consolidated into `wgr-013`; the kept tweak ships the same setting.',
                "canonical": 'wgr-013'},
    "wgr-009": {"name": 'DirectStorage Check',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wgr-010": {"name": '8-bit Color Depth for Performance',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wgr-011": {"name": 'Disable Desktop Composition Overlay',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wifi-006": {"name": 'Use Ethernet for Competitive Play',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wifi-013": {"name": 'Reduce Wi-Fi Packet Queue',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},
    "wifi-014": {"name": 'Disable Preferred Network Promotion',
                "reason": 'Purely informational entry: guidance/advice text with no PC modification and no diagnostic check. Removed so every remaining catalogue entry either applies a real change or performs a real check.',
                "canonical": None},

    # ── Final release audit, 2026-10-08 ────────────────────────────
    "cpu_amd_decrease_policy": {"name": "Performance Decrease Policy (AMD)",
                "reason": "Vendor-gated duplicate of `perf-034` (same boost decrease-policy value); perf-034 ships as the single shared card.",
                "canonical": "perf-034"},
    "cpu_amd_decrease_threshold": {"name": "Performance Decrease Threshold (AMD)",
                "reason": "Vendor-gated duplicate of `cpu_intel_decrease_threshold` (same target and value); the shared cross-vendor card ships instead.",
                "canonical": "cpu_intel_decrease_threshold"},
    "cpu_amd_increase_policy": {"name": "Performance Increase Policy (AMD)",
                "reason": "Vendor-gated duplicate of `cpu_intel_increase_policy` (same target and value); the shared cross-vendor card ships instead.",
                "canonical": "cpu_intel_increase_policy"},
    "cpu_amd_increase_threshold": {"name": "Performance Increase Threshold (AMD)",
                "reason": "Vendor-gated duplicate of `cpu_intel_increase_threshold` (same target and value); the shared cross-vendor card ships instead.",
                "canonical": "cpu_intel_increase_threshold"},
    "cpu_intel_decrease_policy": {"name": "Performance Decrease Policy (Intel)",
                "reason": "Exact duplicate of `perf-034` (same boost decrease-policy value); perf-034 ships instead.",
                "canonical": "perf-034"},
    "dd-015": {"name": "Optimize Network Interrupt Moderation",
                "reason": "Exact duplicate of `net-020` (same adapter interrupt-moderation actions); net-020 ships instead.",
                "canonical": "net-020"},
    "diag-002": {"name": "Open DirectX Diagnostic",
                "reason": "Exact duplicate of `dx-001` (both launch dxdiag); dx-001 ships instead.",
                "canonical": "dx-001"},
    "fpsb-025": {"name": "Disable NTFS Last Access Timestamps",
                "reason": "Exact duplicate of `stor-016` (same fsutil last-access target); stor-016 ships instead.",
                "canonical": "stor-016"},
    "gpu-024": {"name": "Disable DWM Visual Effects",
                "reason": "Gated duplicate of `lap-053` (same DWM ForceEffectMode value); lap-053 ships ungated with an honest name.",
                "canonical": "lap-053"},
    "mouse-059": {"name": "Restart Explorer for Pointer UI",
                "reason": "Exact duplicate of `expl-014` (same explorer restart); expl-014 ships instead.",
                "canonical": "expl-014"},
    "perf-013": {"name": "Disable NIC Interrupt Moderation",
                "reason": "Exact duplicate of `net-020` (same adapter interrupt-moderation actions); net-020 ships instead.",
                "canonical": "net-020"},
    "perf-042": {"name": "Disable Memory Compression (Cmd)",
                "reason": "Exact duplicate of `perf-004` (same MMAgent target); perf-004 ships instead with its commands fixed to run under PowerShell.",
                "canonical": "perf-004"},
    "power-006": {"name": "Disable Hibernation",
                "reason": "Exact duplicate of `perf-008` (`powercfg /hibernate off`); perf-008 ships instead.",
                "canonical": "perf-008"},
    "process_priority": {"name": "Foreground Priority Boost",
                "reason": "Exact duplicate of `adv-006` (same Win32PrioritySeparation target and value); adv-006 ships instead.",
                "canonical": "adv-006"},
    "ram-003": {"name": "Disable SysMain on SSD",
                "reason": "Duplicate SysMain disable (SSD-gated); `perf-005` ships as the single canonical disable.",
                "canonical": "perf-005"},
    "ram-008": {"name": "Disable Hibernation Reserve",
                "reason": "Duplicate hibernation-off card (laptop-gated `powercfg /h`); `perf-008` ships instead.",
                "canonical": "perf-008"},
    "stor-001": {"name": "Enable SSD TRIM",
                "reason": "Exact duplicate of `perf-037` (same fsutil TRIM target and value); perf-037 ships instead.",
                "canonical": "perf-037"},
    "svc-001": {"name": "Disable SysMain",
                "reason": "Duplicate SysMain disable (audit REWRITE resolution); `perf-005` ships as the single canonical disable.",
                "canonical": "perf-005"},
}
