"""Generated audit classification for every tweak (do not edit by hand).
Regenerate with _dev/audit_gen.py."""

OVERRIDES = {
    'adv-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'adv-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-007': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID'},
    'adv-008': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'adv-009': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID'},
    'aim-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'audio-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'AUDIO'},
    'audio-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'AUDIO'},
    'audio-006': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-007': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'audio-008': {'status': 'VALID', 'target': 'AUDIO', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-005': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-008': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bg-009': {'status': 'VALID', 'target': 'STARTUP'},
    'bg-010': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'bios-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'db-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'diag-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'diag-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'disp-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'disp-012': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'dx-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'dx-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'eth-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'eth-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'exp-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'exp-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'expl-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-008': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'expl-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'expl-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'fn-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-018': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-019': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-020': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-021': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-022': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-023': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-024': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-025': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-026': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-027': {'status': 'HARDWARE-SPECIFIC', 'target': 'GAME'},
    'fn-028': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-029': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-030': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-031': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-032': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-033': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-034': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-035': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-036': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-037': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'fn-038': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'game-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GAME'},
    'game-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'GAME'},
    'gpu-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'gpu-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'GPU'},
    'il-006': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'il-007': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-003': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'int-009': {'status': 'VALID', 'target': 'CPU', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'kbd-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'kbd-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'kbd-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mon-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'DISPLAY'},
    'mon-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'mon-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'DISPLAY'},
    'mon-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'mouse-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'mouse-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'net-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'NETWORK'},
    'net-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-009': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'NETWORK'},
    'net-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-012': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'net-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'net-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'nv-001': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'nv-002': {'status': 'HARDWARE-SPECIFIC', 'target': 'GPU'},
    'perf-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'RAM'},
    'power-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'power-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'POWER'},
    'pre-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-003': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'pre-005': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'pre-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'pre-009': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'priv-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'priv-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'ram-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'RAM'},
    'ram-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'ram-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'RAM'},
    'reg-001': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-004': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-006': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-012': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'reg-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'reg-016': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'rep-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-005': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'rep-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'rep-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sec-010': {'status': 'VALID', 'target': 'INFORMATIONAL', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'sec-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'start-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STARTUP'},
    'start-012': {'status': 'VALID', 'target': 'STARTUP', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'stor-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STORAGE'},
    'stor-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'STORAGE'},
    'stor-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'stor-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'STORAGE'},
    'svc-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-005': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-006': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-007': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-010': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-011': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-012': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-013': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'svc-016': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'SERVICES'},
    'sys-002': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-013': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-015': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'sys-016': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'sys-019': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'tel-002': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'TELEMETRY'},
    'tel-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-009': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'TELEMETRY'},
    'tel-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tel-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'TELEMETRY'},
    'tools-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-005': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-007': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-011': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-013': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'tools-014': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DIAGNOSTICS'},
    'usb-001': {'evidence': 'MEDIUM', 'verdict': 'SHIP', 'status': 'VALID', 'target': 'INPUT'},
    'usb-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'usb-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'usb-006': {'status': 'VALID', 'target': 'INPUT', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'usb-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'INPUT'},
    'wgr-003': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wgr-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'DISPLAY'},
    'wgr-012': {'status': 'VALID', 'target': 'DISPLAY', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-001': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-002': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-003': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-004': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-005': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-007': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-009': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-010': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'wifi-011': {'status': 'VALID', 'target': 'NETWORK', 'evidence': 'HIGH', 'verdict': 'REVIEW'},
    'wifi-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN', 'target': 'NETWORK'},
    'win-005': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-006': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-007': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-008': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-009': {'status': 'VALID'},
    'win-012': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-013': {'status': 'VALID', 'win': '10'},
    'win-014': {'evidence': 'HIGH', 'verdict': 'SHIP', 'status': 'VALID'},
    'win-015': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-017': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    'win-018': {'evidence': 'LOW', 'verdict': 'REVIEW', 'status': 'UNKNOWN'},
    # -- 500->60->500 FPS collapse investigation (hand-audited) ----------------
    # fpsb-004 is guidance now: the old PerfLevelSrc/PowerMizerLevel writes
    # were undocumented, driver-version dependent, and hard-coded to a
    # display-adapter instance that is not reliable across PCs. Use the
    # NVIDIA Control Panel profile instead.
}

NOTES = {
    'adv-003': 'obscure registry write - evidence low',
    'adv-006': 'registry target is a known Windows key',
    'adv-007': 'verifiable via live system state',
    'adv-008': 'informational guidance entry',
    'adv-009': 'verifiable via live system state',
    'aim-002': 'obscure registry write - evidence low',
    'audio-001': 'obscure registry write - evidence low',
    'audio-002': 'obscure registry write - evidence low',
    'audio-003': 'obscure registry write - evidence low',
    'audio-004': 'obscure registry write - evidence low',
    'audio-005': 'verifiable via live system state',
    'audio-006': 'informational guidance entry',
    'audio-007': 'informational guidance entry',
    'audio-008': 'informational guidance entry',
    'bg-005': 'informational guidance entry',
    'bg-008': 'informational guidance entry',
    'bg-009': "Tips/Suggestions mechanism; kept valid for supported Windows where present.",
    'bg-010': 'informational guidance entry',
    'bios-001': 'obscure registry write - evidence low',
    'db-001': 'obscure registry write - evidence low',
    'db-002': 'obscure registry write - evidence low',
    'db-003': 'obscure registry write - evidence low',
    'db-004': 'obscure registry write - evidence low',
    'db-005': 'obscure registry write - evidence low',
    'db-006': 'obscure registry write - evidence low',
    'db-014': 'obscure registry write - evidence low',
    'diag-001': 'obscure registry write - evidence low',
    'diag-003': 'obscure registry write - evidence low',
    'diag-004': 'obscure registry write - evidence low',
    'diag-005': 'obscure registry write - evidence low',
    'diag-006': 'obscure registry write - evidence low',
    'diag-007': 'obscure registry write - evidence low',
    'diag-008': 'obscure registry write - evidence low',
    'diag-009': 'obscure registry write - evidence low',
    'diag-010': 'obscure registry write - evidence low',
    'diag-011': 'obscure registry write - evidence low',
    'diag-012': 'obscure registry write - evidence low',
    'diag-014': 'obscure registry write - evidence low',
    'disp-002': 'obscure registry write - evidence low',
    'disp-004': 'obscure registry write - evidence low',
    'disp-005': 'obscure registry write - evidence low',
    'disp-009': 'obscure registry write - evidence low',
    'disp-012': 'informational guidance entry',
    'dx-001': 'obscure registry write - evidence low',
    'dx-003': 'obscure registry write - evidence low',
    'eth-001': 'obscure registry write - evidence low',
    'eth-004': 'obscure registry write - evidence low',
    'eth-005': 'obscure registry write - evidence low',
    'eth-006': 'obscure registry write - evidence low',
    'eth-008': 'obscure registry write - evidence low',
    'eth-009': 'obscure registry write - evidence low',
    'eth-010': 'obscure registry write - evidence low',
    'eth-011': 'obscure registry write - evidence low',
    'eth-012': 'obscure registry write - evidence low',
    'eth-013': 'obscure registry write - evidence low',
    'eth-014': 'obscure registry write - evidence low',
    'exp-001': 'obscure registry write - evidence low',
    'exp-002': 'obscure registry write - evidence low',
    'exp-003': 'obscure registry write - evidence low',
    'exp-004': 'obscure registry write - evidence low',
    'exp-005': 'obscure registry write - evidence low',
    'expl-001': 'obscure registry write - evidence low',
    'expl-002': 'obscure registry write - evidence low',
    'expl-003': 'obscure registry write - evidence low',
    'expl-004': 'registry target is a known Windows key',
    'expl-005': 'obscure registry write - evidence low',
    'expl-006': 'obscure registry write - evidence low',
    'expl-007': 'obscure registry write - evidence low',
    'expl-008': 'registry target is a known Windows key',
    'expl-009': 'obscure registry write - evidence low',
    'expl-010': 'obscure registry write - evidence low',
    'expl-011': 'obscure registry write - evidence low',
    'expl-012': 'obscure registry write - evidence low',
    'expl-013': 'obscure registry write - evidence low',
    'expl-014': 'obscure registry write - evidence low',
    'fn-011': 'obscure registry write - evidence low',
    'fn-012': 'obscure registry write - evidence low',
    'fn-013': 'obscure registry write - evidence low',
    'fn-014': 'obscure registry write - evidence low',
    'fn-015': 'obscure registry write - evidence low',
    'fn-016': 'obscure registry write - evidence low',
    'fn-017': 'obscure registry write - evidence low',
    'fn-018': 'obscure registry write - evidence low',
    'fn-019': 'obscure registry write - evidence low',
    'fn-020': 'obscure registry write - evidence low',
    'fn-021': 'obscure registry write - evidence low',
    'fn-022': 'obscure registry write - evidence low',
    'fn-023': 'obscure registry write - evidence low',
    'fn-024': 'applies only to specific GPU/CPU vendor',
    'fn-025': 'obscure registry write - evidence low',
    'fn-026': 'applies only to specific GPU/CPU vendor',
    'fn-027': 'applies only to specific GPU/CPU vendor',
    'fn-028': 'obscure registry write - evidence low',
    'fn-029': 'obscure registry write - evidence low',
    'fn-030': 'obscure registry write - evidence low',
    'fn-031': 'obscure registry write - evidence low',
    'fn-032': 'obscure registry write - evidence low',
    'fn-033': 'obscure registry write - evidence low',
    'fn-034': 'obscure registry write - evidence low',
    'fn-035': 'obscure registry write - evidence low',
    'fn-036': 'obscure registry write - evidence low',
    'fn-037': 'obscure registry write - evidence low',
    'fn-038': 'obscure registry write - evidence low',
    'game-001': 'obscure registry write - evidence low',
    'game-003': 'known Windows GameDVR/GameBar capture keys',
    'gpu-001': 'obscure registry write - evidence low',
    'gpu-002': 'obscure registry write - evidence low',
    'gpu-003': 'obscure registry write - evidence low',
    'il-006': 'informational guidance entry',
    'il-007': 'informational guidance entry',
    'int-003': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'int-009': 'applies only to specific GPU/CPU vendor; informational guidance entry',
    'kbd-001': 'registry target is a known Windows key',
    'kbd-003': 'obscure registry write - evidence low',
    'kbd-004': 'obscure registry write - evidence low',
    'kbd-005': 'obscure registry write - evidence low',
    'kbd-006': 'obscure registry write - evidence low',
    'mon-001': 'verifiable via live system state',
    'mon-003': 'obscure registry write - evidence low',
    'mon-006': 'verifiable via live system state',
    'mon-014': 'obscure registry write - evidence low',
    'mouse-002': 'obscure registry write - evidence low',
    'mouse-004': 'registry target is a known Windows key',
    'net-002': 'obscure registry write - evidence low',
    'net-003': 'obscure registry write - evidence low',
    'net-004': 'obscure registry write - evidence low',
    'net-005': 'obscure registry write - evidence low',
    'net-006': 'obscure registry write - evidence low',
    'net-007': 'registry target is a known Windows key',
    'net-008': 'obscure registry write - evidence low',
    'net-009': 'registry target is a known Windows key',
    'net-010': 'obscure registry write - evidence low',
    'net-012': 'informational guidance entry',
    'net-013': 'obscure registry write - evidence low',
    'net-014': 'obscure registry write - evidence low',
    'net-015': 'obscure registry write - evidence low',
    'net-016': 'obscure registry write - evidence low',
    'nv-001': 'applies only to specific GPU/CPU vendor',
    'nv-002': 'applies only to specific GPU/CPU vendor',
    'perf-005': 'verifiable via live system state',
    'power-002': 'obscure registry write - evidence low',
    'power-003': 'obscure registry write - evidence low',
    'power-004': 'obscure registry write - evidence low',
    'power-005': 'obscure registry write - evidence low',
    'power-009': 'obscure registry write - evidence low',
    'power-010': 'obscure registry write - evidence low',
    'power-011': 'obscure registry write - evidence low',
    'pre-001': 'registry target is a known Windows key',
    'pre-003': 'registry target is a known Windows key',
    'pre-004': 'obscure registry write - evidence low',
    'pre-005': 'registry target is a known Windows key',
    'pre-006': 'registry target is a known Windows key',
    'pre-007': 'obscure registry write - evidence low',
    'pre-009': 'registry target is a known Windows key',
    'priv-001': 'obscure registry write - evidence low',
    'priv-002': 'obscure registry write - evidence low',
    'priv-003': 'obscure registry write - evidence low',
    'priv-004': 'obscure registry write - evidence low',
    'priv-005': 'obscure registry write - evidence low',
    'priv-006': 'obscure registry write - evidence low',
    'priv-008': 'obscure registry write - evidence low',
    'priv-009': 'obscure registry write - evidence low',
    'priv-010': 'obscure registry write - evidence low',
    'priv-011': 'obscure registry write - evidence low',
    'ram-001': 'obscure registry write - evidence low',
    'ram-002': 'verifiable via live system state',
    'ram-004': 'obscure registry write - evidence low',
    'ram-005': 'obscure registry write - evidence low',
    'ram-009': 'obscure registry write - evidence low',
    'ram-012': 'obscure registry write - evidence low',
    'ram-014': 'obscure registry write - evidence low',
    'reg-001': 'registry target is a known Windows key',
    'reg-002': 'obscure registry write - evidence low',
    'reg-003': 'obscure registry write - evidence low',
    'reg-004': 'registry target is a known Windows key',
    'reg-005': 'obscure registry write - evidence low',
    'reg-006': 'registry target is a known Windows key',
    'reg-007': 'obscure registry write - evidence low',
    'reg-008': 'obscure registry write - evidence low',
    'reg-009': 'obscure registry write - evidence low',
    'reg-010': 'obscure registry write - evidence low',
    'reg-011': 'obscure registry write - evidence low',
    'reg-012': 'registry target is a known Windows key',
    'reg-013': 'obscure registry write - evidence low',
    'reg-014': 'obscure registry write - evidence low',
    'reg-015': 'obscure registry write - evidence low',
    'reg-016': 'registry target is a known Windows key',
    'rep-001': 'obscure registry write - evidence low',
    'rep-002': 'obscure registry write - evidence low',
    'rep-003': 'obscure registry write - evidence low',
    'rep-004': 'obscure registry write - evidence low',
    'rep-005': 'informational guidance entry',
    'rep-007': 'obscure registry write - evidence low',
    'rep-008': 'obscure registry write - evidence low',
    'rep-009': 'obscure registry write - evidence low',
    'rep-013': 'obscure registry write - evidence low',
    'rep-014': 'obscure registry write - evidence low',
    'sec-001': 'obscure registry write - evidence low',
    'sec-002': 'obscure registry write - evidence low',
    'sec-008': 'obscure registry write - evidence low',
    'sec-009': 'obscure registry write - evidence low',
    'sec-010': 'informational guidance entry',
    'sec-011': 'obscure registry write - evidence low',
    'start-001': 'obscure registry write - evidence low',
    'start-005': 'obscure registry write - evidence low',
    'start-012': 'informational guidance entry',
    'stor-002': 'obscure registry write - evidence low',
    'stor-004': 'obscure registry write - evidence low',
    'stor-005': 'verifiable via live system state',
    'stor-006': 'verifiable via live system state',
    'stor-007': 'obscure registry write - evidence low',
    'stor-008': 'obscure registry write - evidence low',
    'stor-009': 'obscure registry write - evidence low',
    'stor-010': 'obscure registry write - evidence low',
    'stor-011': 'obscure registry write - evidence low',
    'svc-002': 'verifiable via live system state',
    'svc-005': 'verifiable via live system state',
    'svc-006': 'verifiable via live system state',
    'svc-007': 'verifiable via live system state',
    'svc-010': 'verifiable via live system state',
    'svc-011': 'verifiable via live system state',
    'svc-012': 'verifiable via live system state',
    'svc-013': 'verifiable via live system state',
    'svc-016': 'verifiable via live system state',
    'sys-002': 'registry target is a known Windows key',
    'sys-004': 'obscure registry write - evidence low',
    'sys-006': 'obscure registry write - evidence low',
    'sys-007': 'registry target is a known Windows key',
    'sys-008': 'obscure registry write - evidence low',
    'sys-009': 'obscure registry write - evidence low',
    'sys-010': 'obscure registry write - evidence low',
    'sys-012': 'obscure registry write - evidence low',
    'sys-013': 'registry target is a known Windows key',
    'sys-014': 'obscure registry write - evidence low',
    'sys-015': 'registry target is a known Windows key',
    'sys-016': 'obscure registry write - evidence low',
    'sys-017': 'obscure registry write - evidence low',
    'sys-019': 'obscure registry write - evidence low',
    'tel-002': 'verifiable via live system state',
    'tel-003': 'obscure registry write - evidence low',
    'tel-004': 'obscure registry write - evidence low',
    'tel-005': 'obscure registry write - evidence low',
    'tel-009': 'verifiable via live system state',
    'tel-010': 'obscure registry write - evidence low',
    'tel-012': 'obscure registry write - evidence low',
    'tel-013': 'obscure registry write - evidence low',
    'tools-001': 'obscure registry write - evidence low',
    'tools-002': 'obscure registry write - evidence low',
    'tools-003': 'obscure registry write - evidence low',
    'tools-004': 'obscure registry write - evidence low',
    'tools-005': 'obscure registry write - evidence low',
    'tools-006': 'obscure registry write - evidence low',
    'tools-007': 'obscure registry write - evidence low',
    'tools-008': 'obscure registry write - evidence low',
    'tools-009': 'obscure registry write - evidence low',
    'tools-010': 'obscure registry write - evidence low',
    'tools-011': 'obscure registry write - evidence low',
    'tools-012': 'obscure registry write - evidence low',
    'tools-013': 'obscure registry write - evidence low',
    'tools-014': 'obscure registry write - evidence low',
    'usb-001': 'verifiable via live system state',
    'usb-003': 'obscure registry write - evidence low',
    'usb-004': 'obscure registry write - evidence low',
    'usb-006': 'informational guidance entry',
    'usb-012': 'obscure registry write - evidence low',
    'wgr-003': 'informational guidance entry',
    'wgr-006': 'obscure registry write - evidence low',
    'wgr-012': 'informational guidance entry',
    'wifi-001': 'obscure registry write - evidence low',
    'wifi-002': 'obscure registry write - evidence low',
    'wifi-003': 'obscure registry write - evidence low',
    'wifi-004': 'obscure registry write - evidence low',
    'wifi-005': 'informational guidance entry',
    'wifi-007': 'informational guidance entry',
    'wifi-008': 'obscure registry write - evidence low',
    'wifi-009': 'obscure registry write - evidence low',
    'wifi-010': 'obscure registry write - evidence low',
    'wifi-011': 'informational guidance entry',
    'wifi-012': 'obscure registry write - evidence low',
    'win-005': 'registry target is a known Windows key',
    'win-006': 'obscure registry write - evidence low',
    'win-007': 'registry target is a known Windows key',
    'win-008': 'obscure registry write - evidence low',
    'win-009': "Tips/Suggestions mechanism; kept valid for supported Windows where present.",
    'win-012': 'obscure registry write - evidence low',
    'win-013': "Win10-era Cortana restriction (kept only for Windows 10 targets).",
    'win-014': 'registry target is a known Windows key',
    'win-015': 'obscure registry write - evidence low',
    'win-017': 'obscure registry write - evidence low',
    'win-018': 'obscure registry write - evidence low',
    # -- 500->60->500 FPS collapse investigation (hand-audited) ----------------
}
